[project]
name = "dvc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.7",
    "mlflow>=3.2.0",
    "prefect>=3.4.12",
]
